const esc = v => String(v ?? "").replace(/[&<>\"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c]);
const q = new URLSearchParams(location.search);
const queryInput = document.querySelector("#stock-query");
const result = document.querySelector("#stock-result");
const flowLink = x => `<a class="master-link" href="../player/?code=${encodeURIComponent(x.player_id)}"><b>${esc(x.alias)}</b><span>查看主力檔案 →</span></a>`;
const delta = x => { const t=x.change_trend||"flat", n=Math.abs(Number(x.change_lots||0)).toLocaleString(); return `<b class="flow-change ${t}">${t==="new"?"新":t==="up"?`↑ ${n} 張`:t==="down"?`↓ ${n} 張`:"—"}</b>`; };
function table(title, rows, kind) { return `<section class="stock-flow ${kind}"><header><div><p>${kind === "buy" ? "TOP 20 NET BUY" : "TOP 20 NET SELL"}</p><h2>${title}</h2></div><small>差異為相同方向相較前一交易日的淨張數</small></header><div class="table-wrap"><table><thead><tr><th>#</th><th>主力</th><th>今日淨張</th><th>較昨日</th><th>淨額</th><th>方向均價</th></tr></thead><tbody>${rows.length ? rows.map((x,i)=>`<tr><td><mark>${String(i+1).padStart(2,"0")}</mark></td><td>${flowLink(x)}</td><td><b>${Number(x.lots).toLocaleString()} 張</b><small>昨日 ${Number(x.previous_lots||0).toLocaleString()} 張</small></td><td>${delta(x)}</td><td>${Number(x.amount_wan).toLocaleString()} 萬</td><td>${Number(x.avg_price).toFixed(2)}</td></tr>`).join(""):`<tr><td colspan="6">本日沒有符合資料</td></tr>`}</tbody></table></div></section>`; }
function render(key, lookup) { const normalized=key.trim().toLowerCase(); if(!normalized){ result.innerHTML="<p class='lookup-empty'>輸入代號或名稱，查看主力買賣階梯。</p>"; return; } const matches=Object.values(lookup).filter(x=>`${x.stock_code} ${x.stock_name}`.toLowerCase().includes(normalized)).slice(0,8); if(!matches.length){ result.innerHTML="<p class='lookup-empty'>查無符合的興櫃個股。</p>"; return; } result.innerHTML=matches.map(item=>`<article class="stock-dossier"><header><div><p>OFFICIAL TPEX FLOW · ${esc(item.stock_code)}</p><h1>${esc(item.stock_name)}</h1></div><dl><div><dt>最新行情</dt><dd>${Number(item.latest_price||0).toFixed(2)}</dd></div><div class="buy"><dt>主力買均價</dt><dd>${Number(item.buys_avg_price||0).toFixed(2)}</dd></div><div class="sell"><dt>主力賣均價</dt><dd>${Number(item.sells_avg_price||0).toFixed(2)}</dd></div></dl></header><section class="leader-strip"><h2>前 10 大主力</h2><div>${item.leaders.map((x,i)=>`<a href="../player/?code=${encodeURIComponent(x.player_id)}"><mark>${String(i+1).padStart(2,"0")}</mark><b>${esc(x.alias)}</b><span>${Number(x.amount_wan).toLocaleString()} 萬</span></a>`).join("")}</div></section>${table("今日前 20 大主力買超",item.buys,"buy")}${table("今日前 20 大主力賣超",item.sells,"sell")}</article>`).join(""); }
fetch("../public/data/dashboard.json",{cache:"no-store"}).then(r=>r.json()).then(d=>{ document.querySelector("#asof").textContent=`行情日：${d.as_of} · 分點資料：${d.latest_flow_date}`; queryInput.value=q.get("q")||""; document.querySelector("#stock-form").addEventListener("submit",e=>{e.preventDefault(); const value=queryInput.value.trim(); history.replaceState(null,"",value?`?q=${encodeURIComponent(value)}`:location.pathname); render(value,d.stock_lookup||{});}); render(queryInput.value,d.stock_lookup||{});}).catch(()=>result.textContent="資料暫時無法載入。");
